# Generated by Django 3.1.3 on 2021-03-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('vk_link', models.TextField(verbose_name='Ссылка на статью для VK API')),
                ('img_link', models.TextField(verbose_name='Картинка')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
                ('public_date', models.DateField(verbose_name='Дата публикации')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(max_length=1, verbose_name='Статус')),
                ('cards', models.ManyToManyField(related_name='cards', to='news.Card', verbose_name='Карточки')),
            ],
        ),
    ]
