# Generated by Django 3.1.3 on 2021-03-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='public_date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='n', max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(default='n', max_length=1, verbose_name='Статус'),
        ),
    ]
